CarWorkShop/ViewModels/DashboardViewModel.cs
using CarWorkShop.Data.Enum;
using CarWorkShop.Models;
using System.Diagnostics;

namespace CarWorkShop.ViewModels
{
    public class DashboardViewModel
    {
        public List<Ticket> Tickets { get; set; }
    }
}

CarWorkShop/Controllers/DashboardController.cs
using CarWorkShop.Data.Interface;
using CarWorkShop.Data.Interfaces;
using CarWorkShop.Models;
using CarWorkShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkShop.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ITicketRepository _ticketRepository;

        public DashboardController(IDashboardRepository dashboardRepository, IHttpContextAccessor httpContextAccessor, ITicketRepository ticketRepository)
        {
            _dashboardRepository = dashboardRepository;
            _httpContextAccessor = httpContextAccessor;
            _ticketRepository = ticketRepository;
        }
        public async Task<IActionResult> Index()
        {
            var userTickets = await _dashboardRepository.GetAllUserTickets();
            var dashboardViewModel = new DashboardViewModel()
            {
                Tickets = userTickets
            };
            return View(dashboardViewModel);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var ticket = await _ticketRepository.GetByIdAsync(id);
            if (ticket == null) return View("Error");
            var ticketVM = new EditTicketViewModel
            {
                Brand = ticket.Brand,
                Model = ticket.Model,
                RegistrationId = ticket.RegistrationId,
                Description = ticket.Description,
                StateCategory = ticket.StateCategory,
                RepairEstimateId = ticket.RepairEstimateId,
            };
            return View(ticketVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditTicketViewModel ticketVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit ticket");
                return View("Edit", ticketVM);
            }

            var userTicket = await _ticketRepository.GetByIdAsyncNoTracking(id);
            if (userTicket == null)
            {
                return View("Error");
            }

            var ticket = new Ticket
            {
                Id = id,
                Brand = ticketVM.Brand,
                Model = ticketVM.Model,
                RegistrationId = ticketVM.RegistrationId,
                Description = ticketVM.Description,
                RepairEstimateId = ticketVM.RepairEstimateId,
                RepairEstimate = ticketVM.RepairEstimate,
            };

            _ticketRepository.Update(ticket);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> EditUserCalender()
        {
            var acceptedTickets = await _dashboardRepository.GetUserAcceptedTickets();
            var dashboardViewModel = new CalenderViewModel()
            {
                AcceptedTickets = acceptedTickets
            };
            return View(dashboardViewModel);
        }
        public async Task<IActionResult> Finish(int id)
        {
            //Get selected ticket
            var ticket = await _ticketRepository.GetByIdAsync(id);

            if (ticket == null) return View("Error");
            //var acceptCalenderVM = new AcceptCalenderViewModel();
            return View(ticket);
        }
        [HttpPost, ActionName("Finish")]
        public async Task<IActionResult> FinishTicket(int id)
        {
            var ticket = await _ticketRepository.GetByIdAsyncNoTracking(id);
            if (ticket == null)
            {
                return View("Error");
            }
            //Update ticket assigned employee and change ticket status
            ticket.StateCategory = CarWorkShop.Data.Enum.StateCategory.Done; 
            _ticketRepository.Update(ticket);
            return RedirectToAction("Index");
        }
    }
}

CarWorkShop/Controllers/TicketController.cs
using CarWorkShop.Data;
using CarWorkShop.Data.Interface;
using CarWorkShop.Data.Interfaces;
using CarWorkShop.Models;
using CarWorkShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkShop.Controllers
{
    public class TicketController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly ITicketRepository _ticketRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IUserRepository _userRepository;
        private readonly IPartRepository _partRepository;
        private readonly ICalenderRepository _calenderRepository;

        public TicketController(ITicketRepository ticketRepository, IHttpContextAccessor httpContextAccessor, IUserRepository userRepository, IPartRepository partRepository, ICalenderRepository calenderRepository)
        {
            //_context = context;
            _ticketRepository = ticketRepository;
            _httpContextAccessor = httpContextAccessor;
            _userRepository = userRepository;
            _partRepository = partRepository;
            _calenderRepository = calenderRepository;
            //_calenderRepository = calenderRepository;
        }
        public async Task<IActionResult> Index()
        {
            //List<Ticket> tickets = _context.Tickets.ToList();
            IEnumerable<Ticket> tickets = await _ticketRepository.GetAll();
            return View(tickets);
        }
        public async Task<IActionResult> Detail(int id)
        {
            //we scan the club table and get the first/default one
            //when we do a join, we need use include(it is expensive)
            Ticket ticket = await _ticketRepository.GetByIdAsync(id);
            return View(ticket);
        }
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createTicketViewModel = new CreateTicketViewModel { UserId = curUserId };
            return View(createTicketViewModel);
        }
        [HttpPost]
        public IActionResult Create(CreateTicketViewModel ticketVM)
        {
            if ((ModelState.IsValid))
            {
                //Create list of parts
               
                var ticket = new Ticket
                {
                    Brand = ticketVM.Brand,
                    Model = ticketVM.Model,
                    RegistrationId = ticketVM.RegistrationId,
                    Description = ticketVM.Description,
                    UserId = ticketVM.UserId,
                    RepairEstimate = new RepairEstimate
                    {
                        Description = ticketVM.RepairEstimate.Description,
                        cost = ticketVM.RepairEstimate.cost,
                        AttitudeCategory = ticketVM.RepairEstimate.AttitudeCategory,
                    },
                    ClientPaid = ticketVM.ClientPaid,
                    PartId = ticketVM.PartId,
                };
                _ticketRepository.Add(ticket);
                return RedirectToAction("Index");
            }
            return View(ticketVM);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var ticket = await _ticketRepository.GetByIdAsync(id);
            if (ticket == null) return View("Error");
            var ticketVM = new EditTicketViewModel
            {
                Brand = ticket.Brand,
                Model = ticket.Model,
                RegistrationId = ticket.RegistrationId,
                Description = ticket.Description,
                StateCategory = ticket.StateCategory,
                RepairEstimateId = ticket.RepairEstimateId,
                ClientPaid = ticket.ClientPaid,
            };
            return View(ticketVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditTicketViewModel ticketVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit ticket");
                return View("Edit", ticketVM);
            }

            var userTicket = await _ticketRepository.GetByIdAsyncNoTracking(id);
            if (userTicket == null)
            {
                return View("Error");
            }

            var ticket = new Ticket
            {
                Id = id,
                Brand = ticketVM.Brand,
                Model = ticketVM.Model,
                RegistrationId = ticketVM.RegistrationId,
                Description = ticketVM.Description,
                RepairEstimateId = ticketVM.RepairEstimateId,
                RepairEstimate = ticketVM.RepairEstimate,
                ClientPaid = ticketVM.ClientPaid,
            };

            _ticketRepository.Update(ticket);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var ticketDetails = await _ticketRepository.GetByIdAsync(id);
            if (ticketDetails == null) return View("Error");
            return View(ticketDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteTicket(int id)
        {
            var ticketDetails = await _ticketRepository.GetByIdAsync(id);
            if (ticketDetails == null) return View("Error");
            _ticketRepository.Delete(ticketDetails);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Accept(int id)
        {
            //We modify ticket state: Created->Processing, And add user's Calender information
            //Get current user
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            User user = await _userRepository.GetUserByIdAsync(curUserId);
            //Get selected ticket
            var ticket = await _ticketRepository.GetByIdAsync(id);
            
            if (ticket == null) return View("Error");
            var acceptCalenderVM = new AcceptCalenderViewModel() {TicketId = ticket.Id };
            return View(acceptCalenderVM);
        }
        [HttpPost]
        public async Task<IActionResult> Accept(int id, AcceptCalenderViewModel acceptCalenderViewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to accept ticket");
                return View("Accept", acceptCalenderViewModel);
            }
            //User operation
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            User user = await _userRepository.GetUserByIdAsync(curUserId);         
            //Add new calender to user
            user.CalenderId = acceptCalenderViewModel.CalenderId;
            var Calender = new Calender
            {
                WeekCategory = acceptCalenderViewModel.WeekCategory,
                FromWhenCategory = acceptCalenderViewModel.FromWhenCategory,
                TillWhenCategory = acceptCalenderViewModel.TillWhenCategory,
                Id = (int)user.CalenderId,
                TicketId = acceptCalenderViewModel.TicketId,
            };
            user.Calender = Calender;
            _userRepository.Update(user);

            //Ticket operation
            var ticket = await _ticketRepository.GetByIdAsyncNoTracking(id);
            if (ticket == null)
            {
                return View("Error");
            }
            //Update ticket assigned employee and change ticket status
            ticket.StateCategory = CarWorkShop.Data.Enum.StateCategory.Processing;
            ticket.EmployeeAssigned = user.Name;
            ticket.AcceptedOrNot = true;
            _ticketRepository.Update(ticket);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Close(int id)
        {
            var ticket = await _ticketRepository.GetByIdAsync(id);
            if (ticket == null) return View("Error");
            //ticket.StateCategory = CarWorkShop.Data.Enum.StateCategory.Closed;
            //_ticketRepository.Update(ticket);
            return View();
        }
        [HttpPost, ActionName("Close")]
        public async Task<IActionResult> CloseTicket(int id)
        {
            var ticket = await _ticketRepository.GetByIdAsyncNoTracking(id);
            if (ticket == null)
            {
                return View("Error");
            }
            //Update ticket assigned employee and change ticket status
            ticket.StateCategory = CarWorkShop.Data.Enum.StateCategory.Closed;
            _ticketRepository.Update(ticket);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> AddParts(int id)
        {
            var ticket = await _ticketRepository.GetByIdAsync(id);
            var partVM = new CreatePartViewModel { TicketId = ticket.Id };
            return View(partVM);
	    }
        [HttpPost, ActionName("AddParts")]
        public async Task<IActionResult> PostParts(CreatePartViewModel partVM)
        {
			if ((ModelState.IsValid))
			{
				//Create list of parts

				var part = new Part
				{
					Name = partVM.Name,
                    Amount = partVM.Amount,
                    UnitPrice = partVM.UnitPrice,
                    TicketId = partVM.TicketId,
				};
				_partRepository.Add(part);
				return RedirectToAction("Index");
			}
			return View(partVM);
		}
        public async Task<IActionResult> PartsDetail(int id)
        {
            var ticketParts = await _partRepository.GetTicketAllParts(id);
            var ticketPrice = ticketParts.Sum(p=>p.Amount * p.UnitPrice);
            var PartDetailViewModel = new PartDetailViewModel()
            {
                Parts = ticketParts,
                TicketPrice = ticketPrice
            };
            return View(PartDetailViewModel);
        }
        public async Task<IActionResult> CalenderDetail(int id)
        {

CarWorkShop/Views/Dashboard/Edit.cshtml
@using CarWorkShop.Data.Enum
@model EditTicketViewModel
@using CarWorkShop.ViewModels

<form method="post" asp-action="Edit">
    <div class="form-group">
        <label asp-for="Brand">Brand</label>
        <input asp-for="Brand" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="brand">
        <span asp-validation-for="Brand" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Model">Model</label>
        <input asp-for="Model" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="model">
        <span asp-validation-for="Model" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RegistrationId">Registration Id</label>
        <input asp-for="RegistrationId" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="registration id">
        <span asp-validation-for="RegistrationId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StateCategory">Ticket Status</label>
        @*Select statement*@
        <select asp-for="StateCategory" asp-items="@Html.GetEnumSelectList<StateCategory>()" class="form-control form-control-lg" disabled>
            <option selected="selected">Created</option>
        </select>
        <span asp-validation-for="StateCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RepairEstimate.Description">Repair estimate description</label>
        <input asp-for="RepairEstimate.Description" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Street">
        <span asp-validation-for="RepairEstimate.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RepairEstimate.cost">Repair estimate cost</label>
        <input asp-for="RepairEstimate.cost" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Street">
        <span asp-validation-for="RepairEstimate.cost" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.RepairEstimate.AttitudeCategory">Client Attitude</label>
        <select asp-for="@Model.RepairEstimate.AttitudeCategory" asp-items="@Html.GetEnumSelectList<AttitudeCategory>()" class="form-control form-control-lg">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="@Model.RepairEstimate.AttitudeCategory" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CarWorkShop/Views/Dashboard/EditUserCalender.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

@model CarWorkShop.ViewModels.CalenderViewModel

<div class="container">
    <div class="jumbotron text-center bg-primary text-white">
        <h1 class="display-4 fw-normal">You Accepted Tickets</h1>
    </div>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                @foreach (var item in Model.AcceptedTickets)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm" style="background-color: lightblue;">
                            <div class="card-body">
                                <h5 class="card-title">@item.Brand - @item.Model</h5>
                                <p class="card-text">@item.Description</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        @* <a type="btn btn-success" asp-controller="Dashboard" asp-action="AddSlot" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Add Slot</a>
                                    <a asp-area="" asp-controller="Dashboard" asp-action="EditSlot" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Change Slot</a>
                                    <a asp-area="" asp-controller="Dashboard" asp-action="DeleteSlot" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete Slot</a> *@
                                        @if (@item.StateCategory.ToString() != "Done" && @item.StateCategory.ToString() != "Closed")
                                        {
                                            <a asp-area="" asp-controller="Dashboard" asp-action="Finish" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Finish</a>
                                            <a asp-controller="Ticket" asp-action="CalenderDetail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View Time</a>
                                        }
                                    </div>
                                    <small class="text-muted">@item.StateCategory</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

CarWorkShop/Views/Dashboard/EditUserProfile.cshtml
@using CarWorkShop.Data.Enum
@using CarWorkShop.ViewModels
@model EditUserDashboardViewModel


<form method="post" asp-action="EditUserProfile" enctype="multipart/form-data">
    <input type="hidden" value="CalenderId" id="CalenderId" />
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CarWorkShop/Views/Dashboard/Finish.cshtml
@using CarWorkShop.Data.Enum
@model Ticket

<h1>Are you sure you want to finish this ticket?</h1>

<form method="post" asp-action="Finish">
    <input type="hidden" id="UserId" name="UserId" asp-for="UserId" />
</form>
<div class="form-group">
    <form action="Finish" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="float-end">
            <input type="submit" style="margin-top:10px" value="Confirm" class="btn btn-primary" />
            <a style="margin-top:10px" class="btn btn-primary" asp-action="Index">Back</a>
        </div>
    </form>
</div>

CarWorkShop/Views/Dashboard/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

@model CarWorkShop.ViewModels.DashboardViewModel

<div class="container">
    <div class="jumbotron text-center bg-primary text-white">
        <h1 class="display-4 fw-normal">User Dashboard</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a type="button" class="btn btn-success btn-lg btn-block" asp-area="" asp-controller="Ticket" asp-action="Create">Create Ticket</a>
        </div>
        <div class="col-md-6">
            <a type="button" class="btn btn-info btn-lg btn-block" asp-area="" asp-controller="Dashboard" asp-action="EditUserCalender">My Calender</a>
        </div>
    </div>
    <div class="album py-5 bg-light">
        <div class="container">
            <h2 class="display-4 fw-normal">You created tickets</h2>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                @foreach (var item in Model.Tickets)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm" style="background-color: lightblue;">
                            <div class="card-body">
                                <h5 class="card-title">@item.Brand - @item.Model</h5>
                                <p class="card-text">@item.Description</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a type="btn btn-success" asp-controller="Ticket" asp-action="Detail" asp-route-id="@item.Id"
                                           class="btn btn-sm btn-outline-secondary">View</a>
                                        @if (SignInManager.IsSignedIn(User))
                                        {
                                            <a asp-area="" asp-controller="Dashboard" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                            <a asp-area="" asp-controller="Ticket" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                        }
                                    </div>
                                    <small class="text-muted">@item.StateCategory</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>